const $ = (s) => document.querySelector(s);
const lessons = [
 {id:'home',title:'1. Startpositie',tag:'BEGINNER',desc:'Plaats je vingers op de basisrij.',keys:'asdfjkl',target:'asdf jkl; asdf jkl; fj fj; dk dk',finger:'Linker wijsvinger op F en rechter wijsvinger op J. Voel de kleine streepjes op F en J zonder naar je toetsenbord te kijken.',tip:'Laat je vingers licht op de toetsen rusten. Je handen blijven ontspannen.'},
 {id:'fingers',title:'2. Juiste vingers',tag:'BEGINNER',desc:'Leer toetsen met de juiste vinger bereiken.',keys:'asdfjkl',target:'fff jjj ddd kkk sss lll aaa ;;;',finger:'Elke vinger heeft een eigen gebied. De wijsvingers bedienen F en J; de andere vingers liggen naast elkaar op de basisrij.',tip:'Beweeg alleen de vinger die nodig is. Breng hem daarna terug naar zijn starttoets.'},
 {id:'top',title:'3. Bovenste rij',tag:'BASIS',desc:'Reik naar de bovenste rij en keer terug.',keys:'azertyuiop',target:'az az er er ty ty ui ui op op',finger:'Reik voorzichtig omhoog vanaf de basisrij. Gebruik de vinger die boven je starttoets ligt en keer na elke aanslag terug.',tip:'Je AZERTY-indeling heeft A-Z-E-R-T-Y op de bovenste letterrij.'},
 {id:'bottom',title:'4. Onderste rij',tag:'BASIS',desc:'Oefen de onderste rij zonder naar je handen te kijken.',keys:'wxcvbn',target:'wx wx cv cv bn bn vw xc nb',finger:'Laat je vingers naar de onderste rij zakken en keer terug naar de basisrij. Gebruik beide handen.',tip:'Langzaam en nauwkeurig is beter dan snel en slordig.'},
 {id:'words',title:'5. Eerste woorden',tag:'WOORDEN',desc:'Maak van losse letters echte woorden.',keys:'abcdefghijklmnopqrstuvwxyz',target:'fiets huis boek water tafel school',finger:'Typ elk woord met de vingers die je net geoefend hebt. Geef de spatiebalk een tik met een duim.',tip:'Kijk naar het scherm, niet naar je vingers.'},
 {id:'caps',title:'6. Hoofdletters',tag:'GEVORDERD',desc:'Gebruik Shift voor hoofdletters.',keys:'shift',target:'Hallo België TypeRush Goede morgen',finger:'Houd Shift met de ene hand ingedrukt en typ de letter met de andere hand. Laat Shift daarna los.',tip:'Gebruik bij voorkeur de Shift-toets aan de andere kant van de letter die je typt.'},
 {id:'punct',title:'7. Leestekens',tag:'GEVORDERD',desc:'Oefen punten, komma’s en vraagtekens.',keys:'punct',target:'Hallo, hoe gaat het? Goed, dank je.',finger:'Leestekens staan op verschillende toetsen van AZERTY. Kijk rustig naar het voorbeeld en gebruik Shift waar nodig.',tip:'Neem je tijd: juiste aanslagen zijn belangrijker dan snelheid.'},
 {id:'sentences',title:'8. Zinnen typen',tag:'UITDAGING',desc:'Combineer alles in een korte zin.',keys:'all',target:'Ik leer stap voor stap blind typen.',finger:'Gebruik de juiste vingers, kijk naar het scherm en houd je schouders ontspannen.',tip:'Je bent klaar om de gewone typetest te proberen wanneer dit vlotter begint te gaan.'}
];
let active=null, step=0, typed='', mistakes=0, attempts=0;
const saved = JSON.parse(localStorage.getItem('typerush-learning') || '{"completed":[],"step":0}');
function persist(){localStorage.setItem('typerush-learning',JSON.stringify(saved));}
function renderHome(){
 $('#learning-home').classList.remove('hidden'); $('#learning-room').classList.add('hidden');
 $('#learning-lessons').innerHTML=lessons.map((l,i)=>`<button class="learning-lesson ${saved.completed.includes(l.id)?'done':''}" data-id="${l.id}"><span class="learning-number">${saved.completed.includes(l.id)?'✓':String(i+1).padStart(2,'0')}</span><span class="learning-lesson-copy"><strong>${l.title}</strong><small>${l.desc}</small></span><span class="learning-tag">${l.tag}</span><span class="learning-arrow">${saved.completed.includes(l.id)?'✓':'→'}</span></button>`).join('');
 $('#learning-lessons').querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>startLesson(b.dataset.id)));
}
function keyboard(target){const keys='1234567890qwertyuiopasdfghjkl;zxcvbnm'.split('');return `<div class="virtual-keyboard" aria-label="Visueel toetsenbord">${keys.map(k=>`<span class="virtual-key ${target.toLowerCase().includes(k)?'key-highlight':''} ${k==='f'||k==='j'?'home-key':''}">${k}</span>`).join('')}</div>`}
function startLesson(id){active=lessons.find(l=>l.id===id);step=0;typed='';mistakes=0;attempts=0;renderStep();}
function renderStep(message=''){
 $('#learning-home').classList.add('hidden');const room=$('#learning-room');room.classList.remove('hidden');
 const chunks=active.target.split(' ');const prompt=chunks[step%chunks.length];
 room.innerHTML=`<button class="text-button" id="lesson-back">← Alle lessen</button><div class="lesson-progress-label"><span>LES ${lessons.findIndex(l=>l.id===active.id)+1} VAN ${lessons.length}</span><span>Oefening ${step+1} van 3</span></div><div class="lesson-progress"><span style="width:${Math.min(100,((step+(saved.completed.includes(active.id)?3:0))/3)*100)}%"></span></div><div class="lesson-instruction"><span class="lesson-big-icon">⌨</span><div><span class="learning-tag">${active.tag}</span><h2>${active.title}</h2><p>${active.finger}</p></div></div><div class="finger-tip"><strong>💡 Onthoud</strong><p>${active.tip}</p></div>${keyboard(active.keys)}<div class="practice-panel"><p class="eyebrow">TYP DIT NA</p><div class="practice-prompt" id="practice-prompt">${[...prompt].map((c,i)=>`<span class="${i<typed.length?(typed[i]===c?'correct':'incorrect'):i===typed.length?'current':''}">${c===' '?'␣':c}</span>`).join('')}</div><input id="practice-input" class="practice-input" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Klik hier en typ de tekst…" aria-label="Typ de oefening"><div class="practice-feedback" id="practice-feedback">${message||'Neem je tijd. Je hoeft niet snel te zijn.'}</div><div class="practice-footer"><span>Fouten: <b>${mistakes}</b></span><button class="primary-button" id="check-practice" ${typed.length===0?'disabled':''}>Controleer oefening →</button></div></div>`;
 $('#lesson-back').onclick=renderHome;const input=$('#practice-input');input.value=typed;input.focus();input.addEventListener('input',()=>{const v=input.value;for(let i=typed.length;i<v.length;i++){attempts++;if(v[i]!==prompt[i])mistakes++;}typed=v;const target=$('#practice-prompt');target.innerHTML=[...prompt].map((c,i)=>`<span class="${i<typed.length?(typed[i]===c?'correct':'incorrect'):i===typed.length?'current':''}">${c===' '?'␣':c}</span>`).join('');$('#check-practice').disabled=typed.length===0;$('#practice-feedback').textContent=typed.length>=prompt.length?'Goed bezig! Klik op controleer om verder te gaan.':'Typ de tekst precies zoals je hem ziet.';});
 $('#check-practice').onclick=()=>{if(typed!==prompt){$('#practice-feedback').textContent='Nog niet helemaal. Vergelijk de gemarkeerde letters en probeer opnieuw.';input.focus();return;}step++;typed='';if(step>=3){if(!saved.completed.includes(active.id))saved.completed.push(active.id);saved.step=Math.max(saved.step,lessons.findIndex(l=>l.id===active.id)+1);persist();$('#learning-room').innerHTML=`<div class="lesson-complete"><div class="lesson-big-icon">✦</div><p class="eyebrow">LES VOLTOOID</p><h2>Goed gedaan!</h2><p>Je hebt ${active.title.toLowerCase()} afgerond. Herhaal de les gerust als je nog meer vertrouwen wilt opbouwen.</p><button class="primary-button" id="next-lesson">${lessons.findIndex(l=>l.id===active.id)<lessons.length-1?'Volgende les →':'Terug naar lessen'}</button><button class="secondary-button" id="lesson-list">Alle lessen</button></div>`;$('#next-lesson').onclick=()=>{const n=lessons[lessons.findIndex(l=>l.id===active.id)+1];n?startLesson(n.id):renderHome()};$('#lesson-list').onclick=renderHome;return;}renderStep('Correct! Goed gedaan — ga door naar de volgende oefening.');};
}
export function initLearning(){renderHome();}
